
import { Oswald } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "@/components/ui/toaster"
import Footer from "@/components/Footer";

const oswald = Oswald({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        
      >
        <div className="fixed top-0 z-50">
          <Navbar />
          {/* <HeroScroll /> */}
        </div>
        {children}
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
